"project_id": "pancancer"
"seed": 42

"project_dir": "/ddn_exa/campbell/sli/methyltrain/data/processed/"
"projects": [
    "TCGA-BLCA",
    "TCGA-BRCA",
    "TCGA-GBM",
    "TCGA-HNSC",
    "TCGA-KIRC"
]

"toggles":
    "MAD_probe_fltering": True
    "batch_correction": False
    "gene_aggregation": False
    "clip_and_scale": True
    "split": True

"MAD_probe_filtering": 30000

"batch_correction":
    "batch_key": "batch_id"
    "covariates": ["project_id"]    # Synonymous with CancerType

"gene_aggregation": ["TSS200", "TSS1500"]    # TSS200, TSS1500, and/or gene_body

"clip_and_scale": [0.01, 0.99]       # For winsorization

"split": [0.60, 0.20, 0.20]
