# Path to the gdc-client executable
"gdc_client": "/ddn_exa/campbell/sli/methyltrain/gdc-client"

"project_id":       "TCGA-UCEC"
"reference_genome": "GRCh38"    # Default for TCGA 450K era
"seed": 42

"download":

    # Fields to filter the DNA methylation data query
    "data_category":         "DNA Methylation"
    "experimental_strategy": "Methylation Array"
    "data_type":             "Methylation Beta Value"
    "platform":              "Illumina Human Methylation 450" 
    "sample_type":           "Primary Tumor"

    # Fields to request from the metadata query
    "metadata": [
        'file_id',
        'file_name',
        'cases.project.project_id',
        'cases.submitter_id',
        'cases.samples.sample_type',
        'data_category',
        'data_type',
        'experimental_strategy',     # e.g. add mutational/clinical metadata
        'platform',                  #  | to query for here for facilitating
        'reference_genome',          #  | further downstream analysis
        'cases.samples.portions.analytes.aliquots.aliquot_id'

    ]

"toggles":

    "sample_qc":        True
    "probe_qc":         True
    "filter_variance":  True     # Filters low variance or extreme probes
    "imputation":       True     # Perform imputation, else default to 0
    "convert_to_mval":  True     # Convert beta values to M-values

"quality_control":
    
    "sample_qc":
        "missing_threshold": 0.20
        "outlier_threshold": 1.5      # Scaling factor for IQR range

    "probe_qc":
        "remove_cross_reactive": True
        "remove_SNP_associated": True
        "remove_sex_chromosome": True
        "remove_multi_mapped": True
        "missing_threshold": 0.05


"preprocessing":

    "filter_variance":
        "min_variance": 0.0001
        "min_mean":     0.01
        "max_mean":     0.99
