# =====| Project Details |======================================================

version: 0.1.0

cohort:
  id: pancancer_v1
  seed: 42

project_dir: "/ddn_exa/campbell/sli/methyltrain/data/processed/"
project_list: [
  "TCGA-BLCA",
  "TCGA-BRCA",
  "TCGA-GBM",
  "TCGA-HNSC",
  "TCGA-KIRC",
  "TCGA-LGG",
  "TCGA-LIHC",
  "TCGA-LUAD",
  "TCGA-LUSC",
  "TCGA-PAAD",
  "TCGA-PRAD",
  "TCGA-SKCM",
  "TCGA-THCA",
  "TCGA-UCEC"
]

# =====| Processing Pipeline |==================================================

"toggles":
    "MAD_probe_filtering": True
    "batch_correction":    False
    "gene_aggregation":    False
    "clip_and_scale":      True
    "split":               True

preprocessing:

  "MAD_probe_filtering": 30000

  "batch_correction":
      "batch_key": "batch_id"
      "covariates": ["project_id"]    # Synonymous with CancerType

  "gene_aggregation": ["TSS200", "TSS1500"]    # TSS200, TSS1500, gene_body

  "clip_and_scale": [0.01, 0.99]       # For winsorization

  "split": [0.60, 0.20, 0.20]
