# =====| Project Details |======================================================

version: 0.1.0

cohort:
  id: test_cohort
  seed: 42

paths:
  output_dir: /Users/sophiali/Desktop/MethylTrain/output
  project_dir: /Users/sophiali/Desktop/MethylTrain/output/projects
  
project_list: [
  "TCGA-GBM",
  "TCGA-SKCM"
]

# =====| Processing Pipeline |==================================================

"toggles":
    "MAD_probe_filtering": True
    "batch_correction":    False
    "gene_aggregation":    False
    "winsorize":           True
    "scale":               True
    "split":               True

preprocessing:

  "MAD_probe_filtering": 30000

  "batch_correction":
      "batch_key": "batch_id"
      "covariates": []    # Synonymous with CancerType

  "gene_aggregation": ["TSS200", "TSS1500"]    # TSS200, TSS1500, gene_body

  "winsorization": 
    "lower": 0.01
    "upper": 0.99

  "split": [0.60, 0.20, 0.20]
